language: java

sudo: false

dist: trusty

jdk:
  - openjdk11

env:
  - TEST_DIR=transpiler JSWEET_VERBOSE=false

script:
  - mvn clean generate-sources

cache:
  directories:
    - $HOME/.m2

install:
  - nvm install 7.5.0 && nvm use 7.5.0

notifications:
  email:
    recipients:
      - louis.grignon@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
